trigger:
  none
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'datainnovation_azuredevops_resourcemanager'
    subscriptionId: 'e59d4026-5b98-4431-8b2e-5e63c9df3fcb'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'dataplatform01-central-p-rg-01'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'jcla-data-factory/ARMTemplateForFactory.json'
    csmParametersFile: 'jcla-data-factory/ARMTemplateParametersForFactory.json'
    overrideParameters: |
      -factoryName "$(factoryName)"
      -connectionToAzureBlobStorage_connectionString "$(connectionToAzureBlobStorage_connectionString)"
    deploymentMode: 'Incremental'